name: Metrics
on:
  # schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - name: 📗 Classic template
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.PERSONAL_TOKEN_MAGICAQUARTET }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: header, activity, community, metadata
          plugins_errors_fatal: ${{ github.repository == 'MagicaQuartet/MagicaQuartet' }}

      - name: 📅 Isocalendar plugin
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.PERSONAL_TOKEN_MAGICAQUARTET }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugins_errors_fatal: ${{ github.repository == 'MagicaQuartet/MagicaQuartet' }}
          
      - name: 🈷️ Languages plugin
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.PERSONAL_TOKEN_MAGICAQUARTET }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_languages: yes
          # plugin_languages_ignored: c, perl, makefile, assembly, glsl, racket, dockerfile, objective-c, c++
          plugin_languages_skipped: "algorithm, CS341, CS376, CS330, CS380, CS420, CS320, CS322, CS230, MagicaQuartet, MagicaQuartet.github.io, productive-box, lowlighter"
          plugins_errors_fatal: ${{ github.repository == 'MagicaQuartet/MagicaQuartet' }}
